<!--
AUTO-GENERATED BY x-change:publish

Source: packages/x-change/resources/js/Accounts.vue

Do not edit this published host copy directly.
Changes will be overwritten by php artisan x-change:publish --scope=build --force.
-->
<script setup lang="ts">
import Accounts from '../../../cockpit/pages/Accounts.vue';
import type { CockpitAccountsPageProps } from '../../../cockpit/types';

const props = defineProps<CockpitAccountsPageProps>();
</script>

<template>
    <Accounts v-bind="props" />
</template>
