<!--
AUTO-GENERATED BY x-change:publish

Source: packages/x-change/resources/js/CampaignWorksheet.vue

Do not edit this published host copy directly.
Changes will be overwritten by php artisan x-change:publish --scope=build --force.
-->
<script setup lang="ts">
import CampaignWorksheet from '../../../cockpit/pages/CampaignWorksheet.vue';

defineOptions({ inheritAttrs: false });
</script>

<template><CampaignWorksheet v-bind="$attrs" /></template>
