<!--
AUTO-GENERATED BY x-change:publish

Source: packages/x-change/resources/js/CampaignPolicyLifecycle.vue

Do not edit this published host copy directly.
Changes will be overwritten by php artisan x-change:publish --scope=build --force.
-->
<script setup lang="ts">
import CampaignPolicyLifecycle from "../../../cockpit/pages/CampaignPolicyLifecycle.vue";
import type { CampaignPolicyLifecycle as CampaignPolicyLifecycleRecord } from "../../../cockpit/campaignPolicyLifecycle";
import type { CockpitHeaderPageProps } from "../../../cockpit/types";

type Props = CockpitHeaderPageProps & {
  lifecycles: CampaignPolicyLifecycleRecord[];
};
const props = defineProps<Props>();
</script>

<template>
  <CampaignPolicyLifecycle v-bind="props" />
</template>
