<!--
AUTO-GENERATED BY x-change:publish

Source: packages/x-change/resources/js/Dashboard.vue

Do not edit this published host copy directly.
Changes will be overwritten by php artisan x-change:publish --scope=build --force.
-->
<script setup lang="ts">
import Dashboard from '../../../cockpit/pages/Dashboard.vue';
import type { CockpitDashboardPageProps } from '../../../cockpit/types';

const props = defineProps<CockpitDashboardPageProps>();
</script>

<template>
    <Dashboard v-bind="props" />
</template>
