<!--
AUTO-GENERATED BY x-change:publish

Source: packages/x-change/resources/js/DistributionWorkspace.vue

Do not edit this published host copy directly.
Changes will be overwritten by php artisan x-change:publish --scope=build --force.
-->
<script setup lang="ts">
import DistributionWorkspace from '../../../cockpit/pages/DistributionWorkspace.vue';
import type { CockpitDistributionWorkspacePageProps } from '../../../cockpit/types';

const props = defineProps<CockpitDistributionWorkspacePageProps>();
</script>

<template>
    <DistributionWorkspace v-bind="props" />
</template>
