<!--
AUTO-GENERATED BY x-change:publish

Source: packages/x-change/resources/js/Documentation.vue

Do not edit this published host copy directly.
Changes will be overwritten by php artisan x-change:publish --scope=build --force.
-->
<script setup lang="ts">
import Documentation from '../../../cockpit/pages/Documentation.vue';

defineOptions({ inheritAttrs: false });
</script>

<template><Documentation v-bind="$attrs" /></template>
