<!--
AUTO-GENERATED BY x-change:publish

Source: packages/x-change/resources/js/Funding.vue

Do not edit this published host copy directly.
Changes will be overwritten by php artisan x-change:publish --scope=build --force.
-->
<script setup lang="ts">
import Funding from '../../../cockpit/pages/Funding.vue';
import type { CockpitFundingPageProps } from '../../../cockpit/types';

const props = defineProps<CockpitFundingPageProps>();
</script>

<template>
    <Funding v-bind="props" />
</template>
