<!--
AUTO-GENERATED BY x-change:publish

Source: packages/x-change/resources/js/PayCodeExplorer.vue

Do not edit this published host copy directly.
Changes will be overwritten by php artisan x-change:publish --scope=build --force.
-->
<script setup lang="ts">
import PayCodeExplorer from '../../../cockpit/pages/PayCodeExplorer.vue';
import type { CockpitPayCodeExplorerPageProps } from '../../../cockpit/types';

const props = defineProps<CockpitPayCodeExplorerPageProps>();
</script>

<template>
    <PayCodeExplorer v-bind="props" />
</template>
