<!--
AUTO-GENERATED BY x-change:publish

Source: packages/x-change/resources/js/QuickGenerate.vue

Do not edit this published host copy directly.
Changes will be overwritten by php artisan x-change:publish --scope=build --force.
-->
<script setup lang="ts">
import QuickGenerate from '../../../cockpit/pages/QuickGenerate.vue';
import type { CockpitQuickGeneratePageProps } from '../../../cockpit/types';

const props = defineProps<CockpitQuickGeneratePageProps>();
</script>

<template>
    <QuickGenerate v-bind="props" />
</template>
