<!--
AUTO-GENERATED BY x-change:publish

Source: packages/x-change/resources/js/RuntimeProfile.vue

Do not edit this published host copy directly.
Changes will be overwritten by php artisan x-change:publish --scope=build --force.
-->
<script setup lang="ts">
import RuntimeProfile from '../../../cockpit/pages/RuntimeProfile.vue';
import type { CockpitRuntimeProfilePageProps } from '../../../cockpit/types';

const props = defineProps<CockpitRuntimeProfilePageProps>();
</script>

<template>
    <RuntimeProfile v-bind="props" />
</template>
