<!--
AUTO-GENERATED BY x-change:publish

Source: packages/x-change/resources/js/VoucherDetail.vue

Do not edit this published host copy directly.
Changes will be overwritten by php artisan x-change:publish --scope=build --force.
-->
<script setup lang="ts">
import VoucherDetail from '../../../cockpit/pages/VoucherDetail.vue';
import type { CockpitVoucherDetailPageProps } from '../../../cockpit/types';

const props = defineProps<CockpitVoucherDetailPageProps>();
</script>

<template>
    <VoucherDetail v-bind="props" />
</template>
